#-*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"

# config.ssh.insert_key = false

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end

  config.vm.synced_folder "vagrant", "/vagrant", type: "virtualbox", mount_options: ["dmode=777", "fmode=666"]

  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.linked_clone = true
  end

  # Ubuntu server
  config.vm.define "centos" do |app|
    app.vm.hostname = "centos"
    app.vm.network :private_network, ip: "192.168.56.4"
  end
end
